# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
    - releases/nneka-terraform-*
  paths:
    include:
    - Terraform/src/*

variables:
  ARTIFACT_NAME: drop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: CopyFiles@2
  displayName: 'Copy terraform Files to artifacts'
  inputs:
    SourceFolder: Terraform/src/dev/
    TargetFolder: '$(build.artifactstagingdirectory)/terraform'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    artifactName: $(ARTIFACT_NAME)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop scripts'
  inputs:
    PathtoPublish: Terraform/src/scripts